-- Principal Section Audit — accept_quote RPC
--
-- Fixes the non-atomic, non-idempotent quote acceptance that could create
-- duplicate orders: the client used to INSERT the order + items and THEN
-- update the quote status in separate round-trips, with no transaction and no
-- guard. A failed status update (or a double click) left an orphan order and
-- allowed a second order to be created from the same quote.
--
-- This RPC does it atomically. It locks the quote row (FOR UPDATE) so
-- concurrent accepts serialize, and returns the existing order if one already
-- exists for the quote (idempotent). Mirrors the design of deliver_order.

CREATE OR REPLACE FUNCTION public.accept_quote(_quote_id uuid)
RETURNS jsonb
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE
  q             record;
  existing_id   uuid;
  existing_num  text;
  new_order_id  uuid;
  order_num     text;
BEGIN
  -- Lock the quote so two concurrent accepts can't both create an order
  SELECT * INTO q FROM public.quotes WHERE id = _quote_id FOR UPDATE;
  IF q IS NULL THEN
    RAISE EXCEPTION 'Devis introuvable' USING ERRCODE = '23503';
  END IF;

  -- Idempotency: if an order already exists for this quote, return it as-is
  SELECT id, order_number INTO existing_id, existing_num
    FROM public.orders WHERE quote_id = _quote_id LIMIT 1;
  IF existing_id IS NOT NULL THEN
    UPDATE public.quotes SET status = 'accepted'
     WHERE id = _quote_id AND status <> 'accepted';
    RETURN jsonb_build_object(
      'order_id', existing_id, 'order_number', existing_num, 'already', true);
  END IF;

  -- 1. Create the order (order_number is generated by the table's own trigger)
  INSERT INTO public.orders (
    customer_id, quote_id, order_date, due_date, status, payment_status,
    total_ttc, paid_amount, stock_applied, notes, created_by
  ) VALUES (
    q.customer_id, q.id, CURRENT_DATE,
    COALESCE(q.expiry_date, (CURRENT_DATE + INTERVAL '30 days')::date),
    'pending', 'unpaid', q.total_ttc, 0, false,
    'Commande générée depuis le devis ' || q.quote_number, auth.uid()
  ) RETURNING id, order_number INTO new_order_id, order_num;

  -- 2. Copy quote_items -> order_items (quote uses discount/total, order uses
  --    discount_rate/line_total_ttc). Quotes carry no warehouse, so it stays null.
  INSERT INTO public.order_items (
    order_id, product_id, description, quantity, unit_price,
    discount_rate, line_total_ttc
  )
  SELECT new_order_id, product_id, description, quantity, unit_price,
         COALESCE(discount, 0), COALESCE(total, 0)
    FROM public.quote_items
   WHERE quote_id = _quote_id;

  -- 3. Mark the quote accepted
  UPDATE public.quotes SET status = 'accepted' WHERE id = _quote_id;

  RETURN jsonb_build_object(
    'order_id', new_order_id, 'order_number', order_num, 'already', false);
END $$;

-- RLS still applies via SECURITY INVOKER
GRANT EXECUTE ON FUNCTION public.accept_quote(uuid) TO authenticated;
